version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - .:/core
    ports:
      - 5173:5173
    image: app:react
    container_name: react_container
    command: npm run dev -- --host